### ISSUE TITLE
JS Source "verstecken"

### ISSUE THREAD

**Issue by TheItCrOw** [TheItCrOw/Bundestags-Mine#7]
Es ist grade der Fall, dass wenn man die Console im Browser öffnet, man den gesamten JS Code in plain text sehen kann. Man kann damit auch einfach die komplette API nachbauen:

![Image](https://user-images.githubusercontent.com/49918134/182846637-d228215e-68bd-42cb-9d08-ce41acf49b4d.png)

Ich kenne das aus anderen Webanwendungen, dass das dort nicht so einfach möglich ist. Ich fände es auch besser, vorallem, wenn wir eine API anbieten wollen, wenn wir unsere Endpunkte besser verstecken und kontrollieren könnten. Hier muss man prolly recherchieren - ich hab ka wie das gemacht wird, dass man net alles einfach in plain text sieht.

**Comment by Eliulm** [comment]
@TheItCrOw - Also folgendes, du kannst die Api nicht direkt verstecken. Weil der Browser muss es irgendwie ja am ende lesen. Du könntest den Source code komprimieren. Dann ist es sehr unleserlich. Das Problem besteht dann aber weiterhin, da du immernoch über den Network Tab die URL abgreifen kannst. 

**Vielleicht können wir das über Sessions lösen. Das also nur durch das Laden einer Website du ein Token bekommst, mit dem du dann alle deine Api calls autorisieren kannst.** Damit kannst du zumindest die Standanlone-Usage der Api vermeiden.

**Comment by TheItCrOw** [comment]
Ja genau, irgendeine Möglichkeit, dass nicht jeder einfach die API nutzen kann, der Bock hat. Sonst werden wir ziemlich gefickt.

Kannst du das mit den Token rausfinden, wie einfach das umzusetzen wäre? Haben das schon oft auf der Arbeit gemacht, war aber nie direkt dran beteiligt leider...

**Comment by Eliulm** [comment]
Ich schau mal - Alles geht mit .NET

**Comment by TheItCrOw** [comment]
Ja, also so wie ich das wollte, mit kompletter Abschattung der API, wird es nicht gehen
https://stackoverflow.com/questions/39589365/having-a-public-api-but-only-allowing-access-to-requests-sent-from-my-website

Man kann es nur bissl schwerer machen und Lizenzen einführen, aber an die API calls kommst du immer... Das mit den Token machts auch "nur" schwerer so wie ich das verstehe
